AnyForum/AnyForum/Controllers/FriendController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AnyForum.Services.Interfaces;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace AnyForum.Controllers
{
    public class FriendController : Controller
    {
        private readonly INotificationService notificationService;
        private readonly UserManager<IdentityUser> userManager;
        private readonly IFriendService friendService;

        public FriendController(INotificationService notificationService, UserManager<IdentityUser> userManager, IFriendService friendService)
        {
            this.notificationService = notificationService;
            this.userManager = userManager;
            this.friendService = friendService;
        }

        public IActionResult AddFriend()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddFriend(string email)
        {
            var userRequest = User.Identity.Name;
            var dbUser = userManager.FindByEmailAsync(userRequest);
            if (userManager.FindByEmailAsync(email).Result == null)
            {
                return RedirectToAction("ActionMessage", "Home", new { Message = $"User with email {email} does not exist. Please check your spelling" });
            }
            if (notificationService.CheckNotification(dbUser.Result.Id, email))
            {
                return RedirectToAction("ActionMessage", "Home", new { Message = $"You have already sent notification to this user - {email}" });
            }
            if (friendService.IsFriendAlready(dbUser.Result.Id, userManager.FindByEmailAsync(email).Result.Id))
            {
                return RedirectToAction("ActionMessage", "Home", new { Message = $"You are already friend with {email}" });
            }
            notificationService.Create(email, dbUser.Result.Id, userRequest);
            return RedirectToAction("ActionMessage", "Home", new { Message = $"Friend request successfuly sent to {email}" });
        }

        public IActionResult Accept(string byUserId)
        {
            var currentUserId = userManager.GetUserId(User);
            var currentDbUser = userManager.FindByIdAsync(currentUserId);
            if (friendService.IsFriendAlready(currentUserId, byUserId))
            {
                notificationService.Delete(byUserId, currentDbUser.Result.Email);
                return RedirectToAction("ActionMessage", "Home", new { Message = $"You are already friend with {userManager.FindByIdAsync(byUserId).Result.Email}" });
            }
            friendService.Create(byUserId, currentUserId);
            notificationService.Delete(byUserId, currentDbUser.Result.Email);
            return RedirectToAction("ActionMessage", "Home", new { Message = $"Friend request accepted. You are now friends with {userManager.FindByIdAsync(byUserId).Result.Email}" });
        }
    }
}

AnyForum/AnyForum/Controllers/NotificationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AnyForum.Helpers;
using AnyForum.Services.Interfaces;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace AnyForum.Controllers
{
    public class NotificationController : Controller
    {
        private readonly INotificationService notificationService;
        private readonly UserManager<IdentityUser> userManager;

        public NotificationController(INotificationService notificationService, UserManager<IdentityUser> userManager)
        {
            this.notificationService = notificationService;
            this.userManager = userManager;
        }

        public IActionResult Overview(string email)
        {
            var username = User.Identity.Name;
            var dbNot = notificationService.GetAll(email);
            var modelList = dbNot.Select(x => ConvertTo.NotificationViewModel(x)).ToList();
            return View(modelList);
        }

        public IActionResult Decline(int id)
        {
            notificationService.Delete(id);
            return RedirectToAction("ActionMessage", "Home", new { Message = $"Friend request declined" });
        }
    }
}

AnyForum/AnyForum/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AnyForum</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AnyForum</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-controller="Home" asp-action="HomePage">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" id="friendBtn" onclick="Toggle()">Friends</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-controller="Notification" asp-action="Overview" asp-route-email="@User.Identity.Name">Notifications</a>
                            </li>
                        }
                        @if (User.IsInRole("admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-controller="Home" asp-action="ForumsForApprove">Approve forums</a>
                            </li>
                        }
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    @*SIDEBAR*@
    <partial name="_SidebarPartial" />
    @*SIDEBAR*@

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

AnyForum/AnyForum/Views/Shared/_SidebarPartial.cshtml
@inject AnyForum.Services.Interfaces.IFriendService friendService
@inject Microsoft.AspNetCore.Identity.UserManager<Microsoft.AspNetCore.Identity.IdentityUser> userManager
@{
    var userId = userManager.GetUserId(User);
    var allFriends = friendService.GetAll(userId);
}
<div class="friendSidebard" id="sidebar">
    <h3 class="sidebarHeader">Friends</h3>

    <div class="sidebardBody">
        <div class="friend">
            <a asp-controller="Friend" asp-action="AddFriend">Add friend</a>
        </div>
        @foreach (var friend in allFriends)
        {
        <a>
            <div class="friend">@userManager.FindByIdAsync(friend.FriendId).Result.Email</div>
        </a>
        }
        <div class="friend">Friend 1</div>
        <div class="friend">Friend 1</div>
        <div class="friend">Friend 1</div>
    </div>
</div>