AnyForum/AnyForum/ViewModels/HomeModels/ActionMessageViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AnyForum.ViewModels.HomeModels
{
    public class ActionMessageViewModel
    {
        public string Message { get; set; }
    }
}

AnyForum/AnyForum/ViewModels/HomeModels/HomePageViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AnyForum.ViewModels.HomeModels
{
    public class HomePageViewModel
    {
        public int Id { get; set; }
        public string ForumTitle { get; set; }
        public DateTime DateCreated { get; set; }
    }
}

AnyForum/AnyForum/Controllers/HomeController.cs
using AnyForum.Helpers;
using AnyForum.Services.Interfaces;
using AnyForum.ViewModels.HomeModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AnyForum.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly IForumService forumService;
        private readonly UserManager<IdentityUser> userManager;

        public HomeController(IForumService forumService, UserManager<IdentityUser> userManager)
        {
            this.forumService = forumService;
            this.userManager = userManager;
        }

        public IActionResult HomePage(string searchInput)
        {
            var viewModelList = new List<HomePageViewModel>();
            if (string.IsNullOrEmpty(searchInput))
            {
                ViewData["header"] = "All forums";
                var dbForums = forumService.GetByStatus(true);
                viewModelList = dbForums.Select(x => ConvertTo.HomePageViewModel(x)).ToList();
            }
            else
            {
                ViewData["header"] = $"Search result for '{searchInput}'";
                var dbSearchForums = forumService.GetSearch(searchInput);
                viewModelList = dbSearchForums.Select(x => ConvertTo.HomePageViewModel(x)).ToList();
            }
            return View(viewModelList);

        }

        [Authorize(Roles = "admin")]
        public IActionResult ForumsForApprove()
        {
            var dbForums = forumService.GetByStatus(false);
            var viewModelList = dbForums.Select(x => ConvertTo.ApproveForumViewModel(x)).ToList();
            return View(viewModelList);
        }

        public IActionResult Approve(int id)
        {
            forumService.Approve(id);
            return RedirectToAction("ForumsForApprove");
        }

        public IActionResult Delete(int id)
        {
            forumService.Remove(id);
            return RedirectToAction("ForumsForApprove");
        }

        public IActionResult ActionMessage(ActionMessageViewModel model)
        {
            return View(model);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(CreateForumViewModel model)
        {
            if (ModelState.IsValid)
            {
                bool isValid = forumService.Validate(model.ForumName);
                if (isValid)
                {
                    var isAdmin = User.IsInRole("admin");
                    var userName = User.Identity.Name;
                    forumService.Create(model.ForumName, model.Description , userName, isAdmin);
                    if (isAdmin)
                    {
                        return RedirectToAction("HomePage");
                    }
                    return RedirectToAction("ActionMessage", new { Message = "Your forum is now sent for approval. Thank you for your contribution" });
                }
                return RedirectToAction("ActionMessage", new { Message = "Forum with similar name already exist. Please use the search input to find this kind of forum." });
            }
            return View(model);
        }
    }
}

AnyForum/AnyForum/Controllers/SingleForumController.cs
using AnyForum.Helpers;
using AnyForum.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace AnyForum.Controllers
{
    [Authorize]
    public class SingleForumController : Controller
    {
        private readonly IForumService forumService;
        private readonly ICommentService commentService;
        private readonly IReplyService replyService;
        private readonly UserManager<IdentityUser> userManager;
        

        public SingleForumController(IForumService forumService,
            ICommentService commentService,
            UserManager<IdentityUser> userManager,
            IReplyService replyService)
        {
            this.forumService = forumService;
            this.commentService = commentService;
            this.userManager = userManager;
            this.replyService = replyService;
        }

        public IActionResult Details(int id, string errorMsg)
        {
            var dbForum = forumService.GetById(id);
            var model = ConvertTo.ForumDetailsViewModel(dbForum);
            if (!string.IsNullOrEmpty(errorMsg))
            {
                model.ErrorMsg = errorMsg;
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Comment(int forumId, string message)
        {
            if (string.IsNullOrEmpty(message))
            {
                return RedirectToAction("Details", new { Id = forumId, ErrorMsg = "You cant submit empty comment. Please try again" });
            }
            var userId = userManager.GetUserId(User);
            var userName = User.Identity.Name;
            commentService.Create(message, forumId, userId, userName);
            return RedirectToAction("Details", new { Id = forumId });
        }

        [HttpPost]
        public IActionResult Reply(int forumId, int commentId, string message)
        {
            if (string.IsNullOrEmpty(message))
            {
                return RedirectToAction("Details", new { Id = forumId, ErrorMsg = "You cant submit empty reply. Please try again" });
            }
            var userName = User.Identity.Name;
            replyService.Create(message, commentId, userName);
            return RedirectToAction("Details", new { Id = forumId });
        }
    }
}

AnyForum/AnyForum/Views/Home/ActionMessage.cshtml
@model AnyForum.ViewModels.HomeModels.ActionMessageViewModel

<br />
<h3>@Model.Message</h3>
<br />
<span>Back to <a asp-controller="Home" asp-action="HomePage">Home page</a></span>

AnyForum/AnyForum/Views/Home/Approve.cshtml
@model List<AnyForum.ViewModels.HomeModels.ApproveForumViewModel>
@section Styles{ 
    <link rel="stylesheet" href="~/css/table.css" />
}

<h3>Approve new forums</h3>

<table class="table">
    <thead>
        <tr>
            <th>Forum name</th>
            <th>Created by</th>
            <th>Date created</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var forum in Model)
	{
        <tr>
            <td>@forum.ForumName</td>
            <td>@forum.CreatedBy</td>
            <td>@forum.DateCreated.ToString("MMMM-dd")</td>
            <td>
                <a class="btn btn-success btn-sm">Approve</a> |
                <a class="btn btn-danger btn-sm">Delete</a> |
                <button class="btn btn-info btn-sm" onclick="ToggleDetails(event)" id="@forum.ForumName">Details</button>
            </td>
        </tr>
        <tr class="hide" id="row-@forum.ForumName">
            <td colspan="4">
                <b><p>Description:</p></b>
                @forum.Description
            </td>
        </tr>
	}
    </tbody>
</table>

@section Scripts{ 
    <script src="~/js/table.js" ></script>
}

AnyForum/AnyForum/Views/Home/Create.cshtml
@model AnyForum.ViewModels.HomeModels.CreateForumViewModel
@section Styles{
    <link rel="stylesheet" href="~/css/form.css" />
}

<br />
<h3>Create our new forum</h3>
<br />
<form asp-action="Create" method="post">
    <span asp-validation-for="ForumName" class="text-danger"></span>
    <input placeholder="Forum name ( Forum theme )" asp-for="ForumName" class="form-control" />
    <br />
    <span asp-validation-for="Description" class="text-danger"></span>
    <textarea placeholder="Short description" asp-for="Description" class="form-control"></textarea>
    <br />
    <input type="submit" value="Create" class="btn btn-success" />
</form>

AnyForum/AnyForum/Views/Home/ForumsForApprove.cshtml
@model List<AnyForum.ViewModels.HomeModels.ApproveForumViewModel>
@section Styles{ 
    <link rel="stylesheet" href="~/css/table.css" />
}

<h3>Approve new forums</h3>

<table class="table">
    <thead>
        <tr>
            <th>Forum name</th>
            <th>Created by</th>
            <th>Date created</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var forum in Model)
	{
        <tr>
            <td>@forum.ForumName</td>
            <td>@forum.CreatedBy</td>
            <td>@forum.DateCreated.ToString("MMMM-dd")</td>
            <td>
                <a class="btn btn-success btn-sm" asp-action="Approve" asp-route-id="@forum.Id">Approve</a> |
                <a class="btn btn-danger btn-sm" asp-action="Delete" asp-route-id="@forum.Id">Delete</a> |
                <button class="btn btn-info btn-sm" onclick="ToggleDetails(event)" id="@forum.ForumName">Details</button>
            </td>
        </tr>
        <tr class="hide" id="row-@forum.ForumName">
            <td colspan="4">
                <b><p>Description:</p></b>
                @forum.Description
            </td>
        </tr>
	}
    </tbody>
</table>

@section Scripts{ 
    <script src="~/js/table.js" ></script>
}

AnyForum/AnyForum/Views/Home/HomePage.cshtml
@model List<AnyForum.ViewModels.HomeModels.HomePageViewModel>
@section Styles{ 
    <link rel="stylesheet" href="~/css/homePage.css" />
}

<div class="container">
    @if (Model.Count == 0)
    {
        <h3>@ViewData["header"]</h3>
        <h5>No forums found</h5>
        <br />
        <span>Back to <a asp-controller="Home" asp-action="HomePage">Home page</a></span>
    }
    else
    {
        <div class="flexContainer">
            <a class="btn btn-outline-success" asp-action="Create">Create forum</a>
            <form asp-action="HomePage">
                <input placeholder="Search forum" name="searchInput" class="form-control" />
                <input type="submit" value="Search" class="btn btn-outline-info" />
            </form>
        </div>
        
        <h3>@ViewData["header"]</h3>
        <div class="forumContainer">

            @foreach (var forum in Model)
            {
                <a class="forumBody" asp-controller="SingleForum" asp-action="Details" asp-route-id="@forum.Id">
                    <h4>@forum.ForumTitle</h4>
                    <span>Views: 12</span>
                    <br />
                    <span>Posts: 123</span>
                    <br />
                    <span>Replyes: 764</span>
                    <br />
                    <span>Created on: @forum.DateCreated.ToString("dd, MMMM, yyyy")</span>
                </a>
            }
        </div>
    }
</div>

AnyForum/AnyForum/Views/Home/Success.cshtml
@model AnyForum.ViewModels.HomeModels.SuccessViewModel

<h3>@Model.Message</h3>
<br />
<span>Back to <a asp-controller="Home" asp-action="HomePage">Home page</a></span>